### ISSUE TITLE
Error when running the "finetuning_training.py"

### ISSUE THREAD

**Issue by imaxpayne** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#11]
Hi, thanks for opening your work.

I converted caffe models and run the embedder_inference without any problem.

But when I run the "finetuning_training.py", the following error happens. 

`Traceback (most recent call last):
  File "finetuning_training.py", line 99, in <module>
    lossG = criterionG(x, x_hat, r_hat, D_res_list, D_hat_res_list)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/Realistic-Neural-Talking-Head-Models/loss/loss_generator.py", line 183, in forward
    loss_cnt = self.LossCnt(x, x_hat)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/Realistic-Neural-Talking-Head-Models/loss/loss_generator.py", line 87, in forward
    self.VGG19(x)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/.local/lib/python3.5/site-packages/torchvision/models/vgg.py", line 44, in forward
    x = self.classifier(x)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/max/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: size mismatch, m1: [1 x 32768], m2: [25088 x 4096] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266`

Do you have any idea what went wrong?

**Comment by imaxpayne** [comment]
I found the problem, it is the `self.VGG19(x)` in loss_generator.py.

The input of the pretrain VGG19 should be in size 224 by 224, but the x is 256 by 256 instead, causing size mismatch problem in FC layer of VGG19.

**Comment by vincent-thevenin** [comment]
Hi @imaxpayne!

I think the problem might not be with VGG19 as there's no error when I run this:
```
from torchvision.models import vgg19

VGG19 = vgg19(pretrained = True)
x = torch.randn(1,3,224,224)
VGG19(x)
```

But you're right about the last fc layers, I made some commits lately to loss generator to drop these  layers in VGG19 after uploading finetuning_training.py. Could you pull the recent changes and tell me if the problem still persists?

As a sidenote, you may want to redo the download for the prerequisites, I also changed the source for the network as the previous one was wrong. This change only makes the network train more efficiently.

**Comment by mumuyanyan** [comment]
> I found the problem, it is the `self.VGG19(x)` in loss_generator.py.
> 
> The input of the pretrain VGG19 should be in size 224 by 224, but the x is 256 by 256 instead, causing size mismatch problem in FC layer of VGG19.

i also have the same question. how to deal with the problem?thank you
