### ISSUE TITLE
finetuning training problem

### ISSUE THREAD

**Issue by mumuyanyan** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#20]
thank you for your open project.
i have the problem when i run the finetuning_training.py

Traceback (most recent call last):
  File "finetuning_training.py", line 99, in <module>
    lossG = criterionG(x, x_hat, r_hat, D_res_list, D_hat_res_list)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nd/workspace/workspace_lsh/face/headmodel/loss/loss_generator.py", line 157, in forward
    loss_cnt = self.LossCnt(x, x_hat)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nd/workspace/workspace_lsh/face/headmodel/loss/loss_generator.py", line 65, in forward
    self.VGG19(x)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torchvision/models/vgg.py", line 39, in forward
    x = self.classifier(x)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/nd/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1 x 32768], m2: [25088 x 4096] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:268

**Comment by vincent-thevenin** [comment]
Hi!
I cannot reproduce your error, I tried running finetuning_training.py for both the image and the video given in the example folder and no error.
Could you print the shape of x before passing through https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/db8095125cb66d8ff4b6bbba7c75a73e5fbf4ecd/loss/loss_generator.py#L65
