### ISSUE TITLE
Error when loading images in embedder_inference.py

### ISSUE THREAD

**Issue by countofkrakow** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#43]
I'm running the code on a Colab notebook with the provided test video and images and I get this error. It also happens when I provide my own images. Help?

Traceback (most recent call last):
  File "embedder_inference.py", line 30, in <module>
    frame_mark_images = select_images_frames(path_to_images)
  File "/content/Realistic-Neural-Talking-Head-Models/dataset/video_extraction_conversion.py", line 101, in select_images_frames
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed)

**Comment by vincent-thevenin** [comment]
Duplicate of #34 . It seems to be an incorrect path when using colab

**Comment by chiazor** [comment]
in colab make sure you are using the full path, it solved it for me
