### ISSUE TITLE
RuntimeError in resume train

### ISSUE THREAD

**Issue by xljh0520** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#69]
I tryto resum training in last checkpoint but met this error. Could you please tell my how to fix it?
```
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    D.module.load_state_dict(checkpoint['D_state_dict'])
  File "/home/ljh/anaconda3/envs/torch12/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Discriminator:
        size mismatch for W_i: copying a param with shape torch.Size([512, 4]) from checkpoint, the shape in current model is torch.Size([512, 32]).

```

**Comment by CHern0g0r** [comment]
I've met the same problem. @xljh0520 have you founded any way to fix it?

**Comment by hanweikung** [comment]
If you are on save_disc branch, change this line
https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/e43ca9fccc297ca048544722aab1a3ee4e9b59f5/train.py#L35
to
```python
D = nn.DataParallel(Discriminator(dataset.__len__(), batch_size, path_to_Wi).to(device))
```
, this line
https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/e43ca9fccc297ca048544722aab1a3ee4e9b59f5/network/model.py#L195
to
```python
def __init__(self, num_videos, batch_size, path_to_Wi, finetuning=False, e_finetuning=None):
```
, and this line
https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/e43ca9fccc297ca048544722aab1a3ee4e9b59f5/network/model.py#L223
to
```python
self.W_i = nn.Parameter(torch.randn(512, batch_size))
```
Then you should be able to resume training from the last saved checkpoint. See #66 

If you also want to fix finetuning training, change this line
https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/e43ca9fccc297ca048544722aab1a3ee4e9b59f5/finetuning_training.py#L44
to
```python
D = Discriminator(dataset.__len__(), batch_size, path_to_Wi, finetuning = True, e_finetuning = e_hat)
```

and this line
https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/blob/e43ca9fccc297ca048544722aab1a3ee4e9b59f5/finetuning_training.py#L76
to
```python
checkpoint['D_state_dict']['W_i'] = torch.rand(512, batch_size) #change W_i for finetuning
```
